### ISSUE TITLE
Invoke-ControlCommand authorization can timeout when using the API key

### ISSUE THREAD

**Issue by DarrenWhite99** [gavsto/AutomateAPI#11]
The API Key is used to create a token that has a time limited validity of about 20 minutes. When using the API Key for authentication, if the command is allowed to run longer than this the token can expire.

This would not stop the remote command from running, but Invoke-ControlCommand would begin to get authorization failures while waiting.

**Comment by DarrenWhite99** [comment]
Addressed in Development Branch. The Token is refreshed as needed during function operation.

**Comment by gavsto** [comment]
Released!
