### ISSUE TITLE
Invoke-ControlCommand online check

### ISSUE THREAD

**Issue by DarrenWhite99** [gavsto/AutomateAPI#12]
If a command is executed against an offline computer, there is no need to wait until the timeout for a result. It should be queued and then the function can exit immediately.

**Comment by DarrenWhite99** [comment]
Supported in Development branch. Function accepts a parameter to control action for offline machines (queue (no waiting), skip (do not send command), wait (send command and wait for timeout)).

**Comment by gavsto** [comment]
Released
