### ISSUE TITLE
Invoke-ControlCommand adaptive polling rate

### ISSUE THREAD

**Issue by DarrenWhite99** [gavsto/AutomateAPI#13]
The function checks for the task to complete with 1 second delays between checks. Commands with very long timeouts could be checked less frequently, especially as time goes on.

Example: If a command could run up to 10 minutes, after 5 minutes of waiting the polling frequency could change to every 5 or 10 seconds with little impact.

**Comment by DarrenWhite99** [comment]
Supported in Development Branch.

**Comment by gavsto** [comment]
Released.
