### ISSUE TITLE
Add reverse search (find agents in Control and not in Automate)

### ISSUE THREAD

**Issue by gavsto** [gavsto/AutomateAPI#15]
Add reverse search (find agents in Control and not in Automate)

**Comment by owenthewizard** [comment]
Is this being worked on?

**Comment by DarrenWhite99** [comment]
This is now supported, by running the following commands:
`$AllSessions=Get-AutomateComputer | Compare-AutomateControlStatus -AllResults -Force
$MissingSessions=$AllSessions | Where-Object {$_.ComputerID -eq 0}`

-Force will test all control sessions (not only the ones provided by Get-AutomateComputer)
-AllResults will return all records processed, not just ones that are offline in Automate and online in Control.
