### ISSUE TITLE
Connect-ControlAPI: Modify url checking

### ISSUE THREAD

**Issue by axiomcs78** [gavsto/AutomateAPI#16]
Modify the url checking to allow urls to contain an arbitrary port number and an arbitrary suffix

**Comment by DarrenWhite99** [comment]
The server validation has been modified in the Development branch. Can you test this again and see if your issue has been resolved?

**Comment by axiomcs78** [comment]
I will not be able to get to this for 2 weeks.

**Comment by gavsto** [comment]
In latest release
