### ISSUE TITLE
Connect-AutomateAPI using -Credential and -TwoFactorToken fails

### ISSUE THREAD

**Issue by DaveKlatka** [gavsto/AutomateAPI#19]
![image](https://user-images.githubusercontent.com/38696743/55357207-723fee80-549a-11e9-9907-693616c38599.png)
When attempting to use pscredentials an error is presented
"Attempt to authenticate to the Automate API has failed with error Cannot validate argument on parameter 'Uri'."

**Comment by DarrenWhite99** [comment]
I believe this is fixed in the current Development branch. I tested the same command line and connected successfully. Can you confirm this is working for you using the Development Branch files?
