### ISSUE TITLE
Enable Mac/Linux support for Control Commands

### ISSUE THREAD

**Issue by gavsto** [gavsto/AutomateAPI#3]
This will involve fixing Invoke-ControlCommand to allow it to deal with returns from Mac and Linux.

**Comment by RMMSecurity** [comment]
Linux restart (For most):

```
#maxlength=100000
#timeout=300000
service ltechagent stop; service ltechagent start; service ltechagent status
```

**Comment by gavsto** [comment]
cwa-lt agent repair via screenconnect (mac os x)
================================================
1. uninstall LT Agent
----------------------
sudo sh /usr/local/ltechagent/uninstaller.sh
2. get dl url
--------------
https://url.com/LabTech/Deployment.aspx?InstallerToken=40c0a74a4d4a40999786b814793eee
3. download (downloads and then renames file to proper name - couldn't find way to do an output instead, but not a huge deal)
-----------
	OS X:
		curl -O  https://url.com/LabTech/Deployment.aspx?InstallerToken=40c0a74a4d4a40999786b814793eee; mv Deployment.aspx?InstallerToken=40c0a74a4d4a40999786b814793eee ltechagent.zip
4. create temp directory and then extract downloaded zip contents to it
------------------------------------------------------------------------
	mkdir lt_temp; unzip -a ltechagent.zip -d /lt_temp
5. install labtech agent via terminal cmd
------------------------------------------
sudo installer -pkg /lt_temp/ltsvc.mpkg -target /
6. view services to confirm successful install
----------------------------------------------
sudo launchctl list | grep com.labtechsoftware; launchctl list | grep com.labtechsoftware
7. delete temp files
---------------------
rm -R lt_temp; rm -R ltechagent.zip

**Comment by DarrenWhite99** [comment]
Commands are able to be sent to OSX agents. But the input should be prepared properly. 
Here is an example command for pulling LTError and agent state information from an OSX computer:
```
Invoke-ControlCommand -Command @'  
[ -f /usr/local/ltechagent/state ]&&(echo '{'  
echo '"state": '; cat /usr/local/ltechagent/state 2>/dev/null  
[ -f /usr/local/ltechagent/agent_config ]&&(cat /usr/local/ltechagent/agent_config | awk 'BEGIN { print ",\"agent_config\": \{"}; { row[NR]= "\"" $1 "\": \"" $2 "\"" }; END { for (i = 1; i < NR; i++) { print row[i] ","}; print row[NR] "\n\}" }')  
[ -f /usr/local/ltechagent/agent.log ]&&(tail -n 100 /usr/local/ltechagent/agent.log | awk 'BEGIN { print ",\"lterrors\": \["}; { gsub ("[\\\\]","\\\\"); gsub ("[\\\"]","\\\""); gsub ("[\\\/]","\\\/"); gsub ("[\\b]","\\b"); gsub ("[\\f]","\\f"); gsub ("[\\t]","\\t"); row[NR]=$0 };   END { for (i = 1; i < NR; i++) { print "\"" row[i] "\","}; print "\"" row[NR] "\"\n\]" }')
echo '}'  
)  
'@.Replace("`r",'') -TimeOut 60000 -MaxLength 102400 
```
The Replace operation is causing the CR (\r) in CRLF line endings to be removed, leaving only LF (\n) characters.
It also could have been done as a single line.
