### ISSUE TITLE
Module prefix naming

### ISSUE THREAD

**Issue by jasonrush** [gavsto/AutomateAPI#30]
Per discussion with @dkattan

```
While we're on the topic of naming, I would like to propose that we begin to use a module prefix to potentially disambiguate our methods from other modules.

-CWControl
-CWManage
-CWAutomate

Similar to how you would use Get-Az* when talking to Azure.
```

I know with the custom module I had started writing (not published anywhere, so no conflicts), I had started using `CWAutomate` as my prefix for this exact reason. I believe there is also a way to set the default prefix, and allow users to override that prefix when they import a module, we probably want to account for that if/when the prefix is modified.

This would also be a functionality-breaking change, unless we include aliases for the existing function names. I'm not sure if we would want to look at starting a new major version at this point, or more likely just add the aliases in the definitions for now?

**Comment by jasonrush** [comment]
Another thought, if we do 3x separate prefixes, does that mean it gets broken into 3x separate modules, then? Or should it get broken into 3x separate modules? If it's all one module, it seems like we should have a single prefix for the entire module, right?

While the naming scheme makes sense in theory, depending on what API is being used, etc, we run into some funkier bits like the `Connect-ControlSession` function where you're connecting to a `Control` session, but you're doing it via the `Automate` API, so where would that function exist? And would it be intuitive enough for end-users?

**Comment by dkattan** [comment]
I don't think it should be 3 separate modules. I don't want to burden the end user with including 3 separately maintained modules that rely on each other to interact. I'd rather one module to talk to all CW services as the defacto standard. There are certainly other modules people have written to do more specific functionality (I was one of them) but as this accumulates critical mass we might be able to convince others to roll their code into it so there's less fragmentation. That's what I'm doing now with a bunch of code I hadn't previously released publicly.

I think we're going to have to take names on a case by case basis when the functionality involves multiple products. I say we keep -CW in the name of the cmdlet, but we name the rest of it as best we can to keep it descriptive.

**Comment by jasonrush** [comment]
So instead of (verb)-(automate/control)(description), moving to (verb)-CW(description)?

If so, the next question would be if something is able to be done via Automate *and* Control (like the powershell stuff, etc), should it be (verb)-CW(automate/control)(description)? Or adding a parameter like `-Method Automate`/`-Method Control` or such?

**Comment by jasonrush** [comment]
After a discussion w/ @dkattan, figured I'd clarify that I was referencing [Import-Module](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/import-module?view=powershell-6#parameters) having a `-Prefix` parameter, and being able to [set an overwritable prefix via variable in the module manifest](https://www.sapien.com/blog/2016/02/15/use-prefixes-to-prevent-command-name-collision/).

**Comment by gavsto** [comment]
We've never managed to come to an agreement on this, it does warrant further discussion but I'm cleaning up issues and closing.
