### ISSUE TITLE
Cache SessionID values from Get-AutomateControlInfo in $script scope variable

### ISSUE THREAD

**Issue by dkattan** [gavsto/AutomateAPI#33]
Since we can only get this information 1 machine at a time, it would be very useful if the module stored it at least for the course of the session as to prevent long lookup times.

**Comment by DarrenWhite99** [comment]
Is this needed?
1 - There is the internal monitor that can lookup the sessionids in bulk, so the one-at-a-time issue is mostly addressed.
2 - "Caching" is already possible. `$X=Get-AutomateComputer | Get-AutomateControlInfo` - Now $X has the session information cached...

Maybe it's just me, but I feel like the value in caching the information is only useful for a short time, like in a script that is performing multiple operations.  But in the context of a single running script it is easy to save the data yourself and use it repeatedly.  If the cache was automatic then you would need to explicitly tell the system to ignore the cached data or you would get results that may not be accurate.  If you instead need to do something explicitly to enable the cache, then why wouldn't you just store the data yourself?

**Comment by dkattan** [comment]
I agree, I didn't occur to me how that monitor worked at the time I created this. I'll close this issue.
