### ISSUE TITLE
Index operation failes; the array index evaluated to null

### ISSUE THREAD

**Issue by trixrahbit** [gavsto/AutomateAPI#39]
Index operation failed; the array index evaluated to null.
At C:\Program Files\WindowsPowerShell\Modules\AutomateAPI\1.1.1\Public\Get-ControlSessions.ps1:99 char:25
+                     If ($_.Date -ge $SCConnected[$_.SessionID]) {
+                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArrayIndex

**Comment by typesynergy** [comment]
Following. Need the same assistance

**Comment by trixrahbit** [comment]
> Following. Need the same assistance

Once I get my head out of my ass I’ll remember how I fixed this. But I think I looked at that line in the code and was able to figure it out so I know it’s solvable and was my fault it didn’t work not the connection.

**Comment by typesynergy** [comment]
Awesome. I was looking at the code but couldn't figure it out myself. So I'm hopeful you can

Kind regards
Brayden Evans

________________________________

**Comment by trixrahbit** [comment]
I think youre not connected to the controlAPI and its not passing the session ID and leaving the value null. 

Make sure you use 

Import the Module (if required)
Import-Module AutomateAPI

Connect to your Automate Server
This is the standard login you would use to log in to the Control Center

Connect-AutomateAPI - follow the prompts If this is successful you will see a message to indicate the token was retrieved successfully.

mine is RMM.************.COM

Connect to your Control Server
Connect-ControlAPI - follow the prompts This doesn't need a token, so it simply stores the credentials temporarily for use later

This should be https://RMM.*************.com:8040


Or whatever your URL is just replace the RMM.**********.COM portions.

Also note that ControlAPI does NOT support MFA and this will not work, however Automate MFA does work.

**Comment by typesynergy** [comment]
![powershell](https://user-images.githubusercontent.com/51340455/73434428-a300e680-433e-11ea-8528-661a8234f8dd.JPG)

Hi - I've definitely connected to control as shown in the attached image. I'm just not sure what more i can do? 

Do you have any other suggestions?

**Comment by trixrahbit** [comment]
For this you’re telling it to compare, but compare what. You need to
specify parameters.

**Comment by typesynergy** [comment]
I'm not telling it to compare. I'm telling it to run the script called compare-Automatecontrolstatus thats stored in the Automateapi module. 

**Get-AutomateComputer -Online $False | Compare-AutomateControlStatus** which should give you a list of Computers that are online in Control and Offline in Automate. You can also run Compare-AutomateControlStatus on its own which will check all machines in Automate.

However none of this works. The **Online- $false** refers to a parameters within that script, i can't add a online parameter to **compare-automatecontrolstatus** as it doesn't contain one. 

If calling the scripts means i'm doing it wrong then there is something wrong with the script

**Comment by trixrahbit** [comment]
I’m saying if I remember correctly you have to tell it a computer to
compare. I don’t think I was able to get it to compare all at once, but
again it’s been a while. I wish control supported MFA and I could test and
see exactly what I did, but again it was one time for it working then we
turned on MFA and haven’t gotten in since.

I believe if you look for the objects first appearing offline then run the
command against that object it’ll somewhat solve the issue. Not sure how to
exactly run against all  and if I did I can’t remember it by now.

I also think I relied heavily on the help built into the module and went
back to the instructions numerous times making sure I followed step by
step.

**Comment by gavsto** [comment]
Get-AutomateComputer -Online $False | Compare-AutomateControlStatus is a command that should work

Can you make sure all your Control extensions are up to date? https://www.gavsto.com/diagnosing-connectwise-control-integration-being-broken-with-connectwise-automate/ I've also pushed some updates recently. If you're having issues after that please re-open.
