### ISSUE TITLE
Issue in Get-ControlSessions

### ISSUE THREAD

**Issue by jonny190** [gavsto/AutomateAPI#50]
`PS C:\WINDOWS\system32> Get-AutomateComputer -ComputerId 13126 | Get-ControlSessions
Get-ControlSessions : The input object cannot be bound to any parameters for the command either because the command
does not take pipeline input or the input and its properties do not match any of the parameters that take pipeline
input.
At line:1 char:42
+ Get-AutomateComputer -ComputerId 13126 | Get-ControlSessions
+                                          ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (@{Id=13126; Loc...ystem.Object[]}:PSObject) [Get-ControlSessions], Par
   ameterBindingException
    + FullyQualifiedErrorId : InputObjectNotBound,Get-ControlSessions

Index operation failed; the array index evaluated to null.
At C:\Program Files\WindowsPowerShell\Modules\AutomateAPI\1.1.3\Public\Get-ControlSessions.ps1:99 char:25
+                     If ($_.Date -ge $SCConnected[$_.SessionID]) {
+                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArrayIndex `

**Comment by DarrenWhite99** [comment]
This should have been addressed in the recent large commit.  Please download the latest master and verify.

Linking to #53 so this issue can be closed when the pull is finalized.
