### ISSUE TITLE
A Partner "ClientID" token

### ISSUE THREAD

**Issue by BassieZ** [gavsto/AutomateAPI#60]
I've noticed I need a ClientID token to get this thing to work. You refer to https://developer.connectwise.com/ClientID but it's behind a login portal. Would it be possible to provide instructions how to get this ClientID token?

Love your work by the way.

**Comment by DarrenWhite99** [comment]
You must register with ConnectWise to get access.

**Comment by BassieZ** [comment]
Ah its for free :-) In that case.... done.
