### ISSUE TITLE
Quiet parameter is not quiet

### ISSUE THREAD

**Issue by BassieZ** [gavsto/AutomateAPI#63]
When using Connect-AutomateAPI -Quiet or connect-ControlAPI -quiet, the output shows "True". So in the end, its not that quiet.

![image](https://user-images.githubusercontent.com/15651371/112653499-c80fbd00-8e4e-11eb-9c79-fe80361b63d2.png)

It might be usefull for scripting to make it really quiet.

**Comment by BassieZ** [comment]
Workaround:
I've modified the Connect-AutomateAPI.ps1 and Connect-ControlAPI.ps1 by removing the Else $true part at the end. This result in a clean output.

**Comment by DarrenWhite99** [comment]
It returns only a status, which is ideal for scriptmg. Pipe to Out-Null, or assign it to $Null to throw away the status if you like. Darren
-------- Original message --------From: BassieZ ***@***.***> Date: 3/26/21  8:18 AM  (GMT-08:00) To: gavsto/AutomateAPI ***@***.***> Cc: Subscribed ***@***.***> Subject: [gavsto/AutomateAPI] Quiet parameter is not quiet (#63) 
When using Connect-AutomateAPI -Quiet or connect-ControlAPI -quiet, the output shows "True". So in the end, its not that quiet.

It might be usefull for scripting to make it really quiet.

**Comment by gavsto** [comment]
Closing this
