### ISSUE TITLE
Get-AutomateComputer does not exist anymore

### ISSUE THREAD

**Issue by VibhuBhatnagarLab** [gavsto/AutomateAPI#66]
please update this document as the commands mentioned in the article do not exist anymore and even if we use the old module the Fix does not work as the base module has been changed.

Regards
Vibhu

**Comment by gavsto** [comment]
Can you please specify further? Get-AutomateComputer absolutely does still exist.

**Comment by VibhuBhatnagarLab** [comment]
HI Gavin

Thanks for your response im happy just to see an email in response of my issues my problem is that the github article is referring to the cmdlets which I cannot find in my PowerShell . I have installed recommended modules for reference screenshot is as below.

***@***.***D74C3E.8F4758E0]

First module has just below commands.
***@***.***D74C3E.D7277690]

Second module has these.

Get-Command -Module ConnectWiseManageAPI

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Function        Connect-CWM                                        0.4.2.0    ConnectWiseManageAPI
Function        ConvertFrom-CWMTime                                0.4.2.0    ConnectWiseManageAPI
Function        ConvertTo-CWMTime                                  0.4.2.0    ConnectWiseManageAPI
Function        Disconnect-CWM                                     0.4.2.0    ConnectWiseManageAPI
Function        Get-CWMAgreement                                   0.4.2.0    ConnectWiseManageAPI
Function        Get-CWMAgreementAddition                           0.4.2.0    ConnectWiseManageAPI
Function        Get-CWMAgreementSite                               0.4.2.0    ConnectWiseManageAPI
Function        Get-CWMAuditTrail                                  0.4.2.0    ConnectWiseManageAPI
Function        Get-CWMBoardStatus                                 0.4.2.0    ConnectWiseManageAPI
Function        Get-CWMBoardStatusNotification                     0.4.2.0    ConnectWiseManageAPI
Function        Get-CWMBoardSubtype                                0.4.2.0    ConnectWiseManageAPI
Function        Get-CWMBoardTeam                                   0.4.2.0    ConnectWiseManageAPI
Function        Get-CWMBoardType                                   0.4.2.0    ConnectWiseManageAPI
Function        Get-CWMCallbackEntry                               0.4.2.0    ConnectWiseManageAPI
Function        Get-CWMChargeCode                                  0.4.2.0    ConnectWiseManageAPI
Function        Get-CWMCompany                                     0.4.2.0    ConnectWiseManageAPI
Function        Get-CWMCompanyConfiguration                        0.4.2.0    ConnectWiseManageAPI
Function        Get-CWMCompanyConfigurationType                    0.4.2.0    ConnectWiseManageAPI
Function        Get-CWMCompanyNote                                 0.4.2.0    ConnectWiseManageAPI
Function        Get-CWMCompanyNoteType                             0.4.2.0    ConnectWiseManageAPI
Function        Get-CWMCompanySite                                 0.4.2.0    ConnectWiseManageAPI
Function        Get-CWMCompanyStatus                               0.4.2.0    ConnectWiseManageAPI
Function        Get-CWMCompanyTeam                                 0.4.2.0    ConnectWiseManageAPI
Function        Get-CWMCompanyTeamRole                             0.4.2.0    ConnectWiseManageAPI
Function        Get-CWMCompanyType                                 0.4.2.0    ConnectWiseManageAPI
Function        Get-CWMCompanyTypeAssociation                      0.4.2.0    ConnectWiseManageAPI
Function        Get-CWMContact                                     0.4.2.0    ConnectWiseManageAPI
Function        Get-CWMDepartment                                  0.4.2.0    ConnectWiseManageAPI
Function        Get-CWMDepartmentLocation                          0.4.2.0    ConnectWiseManageAPI
Function        Get-CWMDocument                                    0.4.2.0    ConnectWiseManageAPI
Function        Get-CWMManufacturer                                0.4.2.0    ConnectWiseManageAPI
Function        Get-CWMMarketingGroupCompany                       0.4.2.0    ConnectWiseManageAPI
Function        Get-CWMMember                                      0.4.2.0    ConnectWiseManageAPI
Function        Get-CWMMyMember                                    0.4.2.0    ConnectWiseManageAPI
Function        Get-CWMMySecurity                                  0.4.2.0    ConnectWiseManageAPI
Function        Get-CWMPriority                                    0.4.2.0    ConnectWiseManageAPI
Function        Get-CWMProduct                                     0.4.2.0    ConnectWiseManageAPI
Function        Get-CWMProductCatalog                              0.4.2.0    ConnectWiseManageAPI
Function        Get-CWMProductComponent                            0.4.2.0    ConnectWiseManageAPI
Function        Get-CWMProductSubCategory                          0.4.2.0    ConnectWiseManageAPI
Function        Get-CWMProductType                                 0.4.2.0    ConnectWiseManageAPI
Function        Get-CWMProject                                     0.4.2.0    ConnectWiseManageAPI
Function        Get-CWMProjectPhase                                0.4.2.0    ConnectWiseManageAPI
Function        Get-CWMProjectSecurityRole                         0.4.2.0    ConnectWiseManageAPI
Function        Get-CWMProjectTeamMember                           0.4.2.0    ConnectWiseManageAPI
Function        Get-CWMProjectTicket                               0.4.2.0    ConnectWiseManageAPI
Function        Get-CWMReport                                      0.4.2.0    ConnectWiseManageAPI
Function        Get-CWMReportColumn                                0.4.2.0    ConnectWiseManageAPI
Function        Get-CWMSalesActivity                               0.4.2.0    ConnectWiseManageAPI
Function        Get-CWMScheduleEntry                               0.4.2.0    ConnectWiseManageAPI
Function        Get-CWMScheduleHoliday                             0.4.2.0    ConnectWiseManageAPI
Function        Get-CWMScheduleHolidayList                         0.4.2.0    ConnectWiseManageAPI
Function        Get-CWMServiceBoard                                0.4.2.0    ConnectWiseManageAPI
Function        Get-CWMServiceBoardInfo                            0.4.2.0    ConnectWiseManageAPI
Function        Get-CWMSource                                      0.4.2.0    ConnectWiseManageAPI
Function        Get-CWMSystemInfo                                  0.4.2.0    ConnectWiseManageAPI
Function        Get-CWMTicket                                      0.4.2.0    ConnectWiseManageAPI
Function        Get-CWMTicketConfiguration                         0.4.2.0    ConnectWiseManageAPI
Function        Get-CWMTicketNote                                  0.4.2.0    ConnectWiseManageAPI
Function        Get-CWMTicketTask                                  0.4.2.0    ConnectWiseManageAPI
Function        Get-CWMTimeEntry                                   0.4.2.0    ConnectWiseManageAPI
Function        Get-CWMTimeSheet                                   0.4.2.0    ConnectWiseManageAPI
Function        New-CWMAgreement                                   0.4.2.0    ConnectWiseManageAPI
Function        New-CWMAgreementAddition                           0.4.2.0    ConnectWiseManageAPI
Function        New-CWMCallbackEntry                               0.4.2.0    ConnectWiseManageAPI
Function        New-CWMCompanyConfiguration                        0.4.2.0    ConnectWiseManageAPI
Function        New-CWMCompanyConfigurationTypeQuestionValue       0.4.2.0    ConnectWiseManageAPI
Function        New-CWMCompanyTeam                                 0.4.2.0    ConnectWiseManageAPI
Function        New-CWMCompanyTypeAssociation                      0.4.2.0    ConnectWiseManageAPI
Function        New-CWMContact                                     0.4.2.0    ConnectWiseManageAPI
Function        New-CWMContactCommunication                        0.4.2.0    ConnectWiseManageAPI
Function        New-CWMDebugReport                                 0.4.2.0    ConnectWiseManageAPI
Function        New-CWMDocument                                    0.4.2.0    ConnectWiseManageAPI
Function        New-CWMMember                                      0.4.2.0    ConnectWiseManageAPI
Function        New-CWMProductCatalog                              0.4.2.0    ConnectWiseManageAPI
Function        New-CWMProjectPhase                                0.4.2.0    ConnectWiseManageAPI
Function        New-CWMProjectTeamMember                           0.4.2.0    ConnectWiseManageAPI
Function        New-CWMScheduleEntry                               0.4.2.0    ConnectWiseManageAPI
Function        New-CWMServiceBoard                                0.4.2.0    ConnectWiseManageAPI
Function        New-CWMTicket                                      0.4.2.0    ConnectWiseManageAPI
Function        New-CWMTicketConfiguration                         0.4.2.0    ConnectWiseManageAPI
Function        New-CWMTicketNote                                  0.4.2.0    ConnectWiseManageAPI
Function        New-CWMTicketTask                                  0.4.2.0    ConnectWiseManageAPI
Function        New-CWMTimeEntry                                   0.4.2.0    ConnectWiseManageAPI
Function        Remove-CWMAgreementSite                            0.4.2.0    ConnectWiseManageAPI
Function        Remove-CWMCallbackEntry                            0.4.2.0    ConnectWiseManageAPI
Function        Remove-CWMCompanyConfiguration                     0.4.2.0    ConnectWiseManageAPI
Function        Remove-CWMCompanyTypeAssociation                   0.4.2.0    ConnectWiseManageAPI
Function        Remove-CWMContact                                  0.4.2.0    ConnectWiseManageAPI
Function        Remove-CWMMarketingGroupCompany                    0.4.2.0    ConnectWiseManageAPI
Function        Remove-CWMScheduleEntry                            0.4.2.0    ConnectWiseManageAPI
Function        Remove-CWMTicket                                   0.4.2.0    ConnectWiseManageAPI
Function        Submit-CWMTimeSheet                                0.4.2.0    ConnectWiseManageAPI
Function        Update-CWMAgreementAddition                        0.4.2.0    ConnectWiseManageAPI
Function        Update-CWMCallbackEntry                            0.4.2.0    ConnectWiseManageAPI
Function        Update-CWMCompany                                  0.4.2.0    ConnectWiseManageAPI
Function        Update-CWMCompanyConfiguration                     0.4.2.0    ConnectWiseManageAPI
Function        Update-CWMCompanyConfigurationTypeQuestionValue    0.4.2.0    ConnectWiseManageAPI
Function        Update-CWMCompanyTypeAssociation                   0.4.2.0    ConnectWiseManageAPI
Function        Update-CWMContact                                  0.4.2.0    ConnectWiseManageAPI
Function        Update-CWMContactCommunication                     0.4.2.0    ConnectWiseManageAPI
Function        Update-CWMMember                                   0.4.2.0    ConnectWiseManageAPI
Function        Update-CWMProductCatalog                           0.4.2.0    ConnectWiseManageAPI
Function        Update-CWMProjectPhase                             0.4.2.0    ConnectWiseManageAPI
Function        Update-CWMProjectTicket                            0.4.2.0    ConnectWiseManageAPI
Function        Update-CWMTicket                                   0.4.2.0    ConnectWiseManageAPI


Am I missing anything is there anything missing that needs to be installed on the machine please guide.

Regards
Vibhu

**Comment by gavsto** [comment]
You are looking at the ConnectWiseManageAPI module there. That's not this module. This is the AutomateAPI module.
