### ISSUE TITLE
Invoke-AutomateAPIMaster : An error has been thrown.

### ISSUE THREAD

**Issue by thelawrencearm** [gavsto/AutomateAPI#67]
I can connect to the api but I can't pull any information. I get misc errors regarding Invoke-AutomateAPIMaster

(tested on multiple computers. PowersShell version: 5.1.19041.546  ) 

Get-AutomateClient - Allclients 
Invoke-AutomateAPIMaster : An error has been thrown.
at Invoke-AutomateAPIMaster<Process>, C:\Users\REDACTED\Documents\WindowsPowerShell\Modules\automateapi\1.1.4\Private\Invoke-AutomateAPIMaster.ps1: line 75
at Get-AutomateAPIGeneric<Process>, C:\Users\REDACTED\Documents\WindowsPowerShell\Modules\automateapi\1.1.4\Public\Get-AutomateAPIGeneric.ps1: line 146
at Get-AutomateClient, C:\Users\REDACTED\Documents\WindowsPowerShell\Modules\automateapi\1.1.4\Public\Get-AutomateClient.ps1: line 85
at <ScriptBlock>, <No file>: line 1
--> 
--> 
At C:\Users\REDACTED\Documents\WindowsPowerShell\Modules\automateapi\1.1.4\Public\Get-AutomateAPIGeneric.ps1:146 char:27
+ ...              $Result = Invoke-AutomateAPIMaster -Arguments $Arguments
+                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-AutomateAPIMaster

**Comment by gavsto** [comment]
Are you a Super Admin? Can you tell me the exactly sequence of commands you ran from opening PowerShell? Your output has a space in the - Allclients too want to make sure that's not related.

**Comment by thelawrencearm** [comment]
Here is what I am running.  I am a super admin in LT. a local admin of the machine I am on.  I get the same error running it on the automate server as well. I have tried downloading the module directly from github and always get the same errors.  AV has been disabled as well.  


PS C:\WINDOWS\system32> Connect-AutomateAPI
Please enter your Automate Server address, IE: rancor.hostedrmm.com: redacted
Please enter API Client ID (Required for 2020.P11 and above): Redacted
Please enter your Automate Username: redacted
Please enter your 2FA Token: redacted
Successfully tested and connected to the Automate REST API. Token will expire at 2021-06-09T22:13:51

PS C:\WINDOWS\system32> Get-AutomateClient -AllClients
Invoke-AutomateAPIMaster : An error has been thrown.
at Invoke-AutomateAPIMaster<Process>, C:\Users\redacted\Documents\WindowsPowerShell\Modules\AutomateAPI\1.1.4\Private\Invoke-AutomateAPIMaster.ps1: line 75
at Get-AutomateAPIGeneric<Process>, C:\Users\redacted\Documents\WindowsPowerShell\Modules\AutomateAPI\1.1.4\Public\Get-AutomateAPIGeneric.ps1: line 146
at Get-AutomateClient, C:\Users\\Documents\WindowsPowerShell\Modules\AutomateAPI\1.1.4\Public\Get-AutomateClient.ps1: line 85
at <ScriptBlock>, <No file>: line 1
--> 
--> 
At C:\Users\\Documents\WindowsPowerShell\Modules\AutomateAPI\1.1.4\Public\Get-AutomateAPIGeneric.ps1:146 char:27
+ ...              $Result = Invoke-AutomateAPIMaster -Arguments $Arguments
+                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-AutomateAPIMaster

**Comment by gavsto** [comment]
Could you try Get-AutomateComputer -ComputerID 12345  

Pick a computer ID you know exists.

**Comment by thelawrencearm** [comment]
PS C:\WINDOWS\system32> Get-AutomateComputer -ComputerID 39569
Invoke-AutomateAPIMaster : An error has been thrown.
at Invoke-AutomateAPIMaster<Process>, C:\Users\redacted\Documents\WindowsPowerShell\Modules\AutomateAPI\1.1.4\Private\Invoke-AutomateAPIMaster.ps1: line 75
at Get-AutomateAPIGeneric<Process>, C:\Users\redacted\Documents\WindowsPowerShell\Modules\AutomateAPI\1.1.4\Public\Get-AutomateAPIGeneric.ps1: line 146
at Get-AutomateComputer, C:\Users\redacted\Documents\WindowsPowerShell\Modules\AutomateAPI\1.1.4\Public\Get-AutomateComputer.ps1: line 413
at <ScriptBlock>, <No file>: line 1
--> 
--> 
At C:\Users\redacted\Documents\WindowsPowerShell\Modules\AutomateAPI\1.1.4\Public\Get-AutomateAPIGeneric.ps1:146 char:27
+ ...              $Result = Invoke-AutomateAPIMaster -Arguments $Arguments
+                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-AutomateAPIMaster

**Comment by gavsto** [comment]
I can't replicate this. I would suggest you step through the code and figure out where it's going wrong and maybe I can give more information from there.

**Comment by BrambleTheBoar** [comment]
Sorry to reopen this Issue.  I'm having the same problem.  Running this from a workstation, not my Automate server if that helps.  Full log from powershell:  

Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Windows\system32> Import-Module AutomateAPI
PS C:\Windows\system32> Connect-AutomateAPI
Please enter your Automate Server address, IE: rancor.hostedrmm.com: https://<Webserver URL>
Please enter API Client ID (Required for 2020.P11 and above): <Redacted>
Please enter your Automate Username: <Redacted>
Please enter your Automate Password: <Redacted>
Please enter your 2FA Token: <Redacted>
Successfully tested and connected to the Automate REST API. Token will expire at 2022-01-07T20:16:34
PS C:\Windows\system32> Connect-ControlAPI
Please enter your Control Server address, the full URL. IE https://control.rancorthebeast.com:8040: http://<Webserver URL>:8040
Please enter your Control Username: <Redacted>
Please enter your Control Password: <Redacted>
Control Extension version 4.3.0.2 enabled: True
Server version is 21.13.5058.7951.
Successfully tested and connected to the Control API.
PS C:\Windows\system32> Get-AutomateComputer -ComputerID 2
Invoke-AutomateAPIMaster : An error has been thrown.
at Invoke-AutomateAPIMaster<Process>, C:\Program
Files\WindowsPowerShell\Modules\AutomateAPI\1.1.5\Private\Invoke-AutomateAPIMaster.ps1: line 75
at Get-AutomateAPIGeneric<Process>, C:\Program
Files\WindowsPowerShell\Modules\AutomateAPI\1.1.5\Public\Get-AutomateAPIGeneric.ps1: line 146
at Get-AutomateComputer, C:\Program Files\WindowsPowerShell\Modules\AutomateAPI\1.1.5\Public\Get-AutomateComputer.ps1:
line 413
at <ScriptBlock>, <No file>: line 1
-->
-->
At C:\Program Files\WindowsPowerShell\Modules\AutomateAPI\1.1.5\Public\Get-AutomateAPIGeneric.ps1:146 char:27
+ ...              $Result = Invoke-AutomateAPIMaster -Arguments $Arguments
+                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-AutomateAPIMaster

PS C:\Windows\system32>

If this needs to be run directly on the Automate server, I'm waiting for a maintenance window to restart the server after updating powershell.  The Powershell version was too low to run Install-Module commands.  We also self host and are using control plugin, not a separate control server if that helps at all.

The initial error from Invoke-AutomateAPIMaster.ps1 is getting hung up on line 75: $Result = Invoke-WebRequest @Arguments

I'm not entirely sure what all goes into the @Arguments field.  Some direction there might help troubleshoot why its throwing an error.
