### ISSUE TITLE
Issue with Get-AutomateComputer or Compare-AutomateControlStatus or Both?

### ISSUE THREAD

**Issue by iwright-navitend** [gavsto/AutomateAPI#69]
Issue with Get-AutomateComputer or Compare-AutomateControlStatus or Both?

WARNING: Property Name is not supported by this version of Control
WARNING: Property CreatedTime is not supported by this version of Control
WARNING: Property GuestOperatingSystemManufacturerName is not supported by this version of Control
WARNING: Property GuestOperatingSystemName is not supported by this version of Control
WARNING: Property CustomProperty1 is not supported by this version of Control
WARNING: Property CustomProperty2 is not supported by this version of Control
WARNING: Property SessionType is not supported by this version of Control

I receive these warnings now when trying to compare or repair. This started after upgrading Control to version: 21.8.3663.7830

Thanks! :-)

**Comment by gavsto** [comment]
This only occurs when the Control API has not been connected to and the Compare-AutomateControlStatus is called. I can't get this to warn when both AutomateAPI and ControlAPI are connected. If you can please walk me through the steps to take to get that error when both are connected. Thanks
